"""add recommended workouts tables

Revision ID: 2020c406a657
Revises: 70cd27014df3
Create Date: 2025-02-09 22:41:38.287308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2020c406a657'
down_revision: Union[str, None] = '70cd27014df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_records',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('exercise_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('repetitions', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sets', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('body_part', mysql.TEXT(), nullable=False),
    sa.Column('input_source', mysql.ENUM('MEMBER', 'TRAINER'), nullable=False),
    sa.Column('member_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('trainer_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name='exercise_records_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['pt_sessions.id'], name='exercise_records_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], name='exercise_records_ibfk_3', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
