"""PT 세션 관리 기능 추가

Revision ID: 612e1eb6df94
Revises: f01cc067ea4a
Create Date: 2025-02-06 16:45:57.637590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '612e1eb6df94'
down_revision: Union[str, None] = 'f01cc067ea4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('total_pt_count', sa.Integer(), nullable=True))
    op.add_column('members', sa.Column('remaining_pt_count', sa.Integer(), nullable=True))
    op.drop_column('members', 'pt_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('pt_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('members', 'remaining_pt_count')
    op.drop_column('members', 'total_pt_count')
    # ### end Alembic commands ###
