"""add_member_fields

Revision ID: 70cd27014df3
Revises: add_sets_to_exercise_records
Create Date: 2025-02-09 21:47:58.265697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '70cd27014df3'
down_revision: Union[str, None] = 'add_sets_to_exercise_records'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_records')
    op.add_column('members', sa.Column('fitness_goal', sa.String(length=100), nullable=False))
    op.add_column('members', sa.Column('experience_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='experiencelevel'), nullable=False))
    op.add_column('members', sa.Column('has_injury', sa.Boolean(), nullable=True))
    op.add_column('members', sa.Column('injury_description', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('session_duration', sa.Integer(), nullable=False))
    op.add_column('members', sa.Column('preferred_exercises', sa.Text(), nullable=True))
    op.alter_column('members', 'gender',
               existing_type=mysql.ENUM('MALE', 'FEMALE'),
               nullable=False)
    op.alter_column('pt_sessions', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pt_sessions', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('members', 'gender',
               existing_type=mysql.ENUM('MALE', 'FEMALE'),
               nullable=True)
    op.drop_column('members', 'preferred_exercises')
    op.drop_column('members', 'session_duration')
    op.drop_column('members', 'injury_description')
    op.drop_column('members', 'has_injury')
    op.drop_column('members', 'experience_level')
    op.drop_column('members', 'fitness_goal')
    op.create_table('exercise_records',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('exercise_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('repetitions', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('body_part', mysql.TEXT(), nullable=False),
    sa.Column('input_source', mysql.ENUM('MEMBER', 'TRAINER'), nullable=False),
    sa.Column('member_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('trainer_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('sets', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name='exercise_records_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['pt_sessions.id'], name='exercise_records_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], name='exercise_records_ibfk_3', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
