"""회원 순번(sequence_number) 필드 추가

Revision ID: f01cc067ea4a
Revises: ace03e8d1ea4
Create Date: 2025-02-06 16:22:56.751926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01cc067ea4a'
down_revision: Union[str, None] = 'ace03e8d1ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('sequence_number', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'members', ['sequence_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='unique')
    op.drop_column('members', 'sequence_number')
    # ### end Alembic commands ###
